# Generated by Django 4.1 on 2022-10-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0012_alter_pedidodetalleclientemodel_options_and_more'),
        ('notificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionmodel',
            name='cuenta_notificada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.cuentamodel', verbose_name='Notifica a:'),
        ),
        migrations.AlterField(
            model_name='notificacionmodel',
            name='prioridad',
            field=models.CharField(choices=[('1', 'ALTA'), ('2', 'MEDIA'), ('3', 'BAJA')], max_length=10, verbose_name='Prioridad'),
        ),
    ]
