# Generated by Django 4.1 on 2022-09-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('nro_identificacion', models.CharField(max_length=20, verbose_name='CIF')),
                ('observaciones', models.CharField(blank=True, default='---', max_length=200, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.RemoveField(
            model_name='pedidomodel',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='cuenta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.cuentamodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.cuentamodel'),
        ),
    ]
