# Generated by Django 4.1 on 2022-09-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_perfil_proveedor_perfil_cuenta'),
        ('distribuidora_app', '0002_cuentamodel_remove_pedidomodel_proveedor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProveedorModel',
        ),
    ]
