# Generated by Django 4.1 on 2022-09-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0003_delete_proveedormodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.cuentamodel'),
        ),
    ]
