# Generated by Django 4.1 on 2022-09-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0005_rename_almacenmodel_entregamodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregamodel',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.cuentamodel'),
        ),
    ]
