# Generated by Django 4.1 on 2022-09-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0006_entregamodel_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenstockmodel',
            name='nro_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.pedidomodel'),
        ),
    ]
