# Generated by Django 4.1 on 2022-09-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0007_almacenstockmodel_nro_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoenventa',
            name='cantidad_venta',
            field=models.IntegerField(default=0, verbose_name='Cantidad en venta'),
        ),
    ]
