# Generated by Django 4.1 on 2022-09-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0009_alter_productoenventa_options_productoalmacenado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDetalleClienteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('cantidad', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.pedidomodel')),
                ('producto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.productoenventa')),
            ],
            options={
                'verbose_name': 'Pedido detalle Cliente',
                'verbose_name_plural': 'Pedidos detalle Clientes',
            },
        ),
    ]
