# Generated by Django 4.1 on 2022-09-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0010_pedidodetalleclientemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidodetalleclientemodel',
            options={'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
        migrations.RemoveField(
            model_name='pedidodetalleclientemodel',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidodetalleclientemodel',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidodetalleclientemodel',
            name='producto_venta',
        ),
    ]
