# Generated by Django 4.1 on 2022-09-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0011_alter_pedidodetalleclientemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidodetalleclientemodel',
            options={'verbose_name': 'Pedido detalle Cliente', 'verbose_name_plural': 'Pedidos detalle Clientes'},
        ),
        migrations.AddField(
            model_name='pedidodetalleclientemodel',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidodetalleclientemodel',
            name='pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.pedidomodel'),
        ),
        migrations.AddField(
            model_name='pedidodetalleclientemodel',
            name='producto_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.productoenventa'),
        ),
    ]
