# Generated by Django 4.1 on 2022-09-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora_app', '0002_cuentamodel_remove_pedidomodel_proveedor_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='perfil',
            name='cuenta',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='distribuidora_app.cuentamodel'),
        ),
    ]
