# Generated by Django 4.1 on 2022-11-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_perfil_cuenta_alter_perfil_is_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerLoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_login', models.BooleanField()),
            ],
        ),
    ]
